AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  InstanceType:
    Default: t2.medium
    Description: Instance Type
    Type: String
  ImageId:
    Default: ami-0fb653ca2d3203ac1
    Description: AMI
    Type: AWS::EC2::Image::Id
  DiskSize:
    Default: 20
    Description: Disk Size
    Type: String
  KeyName:
    Description: Private key
    Type: AWS::EC2::KeyPair::KeyName
  MyIp:
    Description: My IP Address
    Type: String
Resources:
  myASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones:
      - us-east-2a
      - us-east-2b
      MinSize: '0'
      MaxSize: '1'
      DesiredCapacity: '1'
      LaunchTemplate:
        LaunchTemplateId: !Ref myTemplate
        Version: !GetAtt myTemplate.LatestVersionNumber
  myTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: MyLaunchTemplate
      LaunchTemplateData:
        ImageId: !Ref ImageId
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        SecurityGroupIds:
        - !GetAtt Ec2SecurityGroup.GroupId
        BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: !Ref DiskSize
        InstanceMarketOptions:
          MarketType: spot
    DependsOn: Ec2SecurityGroup
  Ec2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow connections
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        CidrIp: !Sub '${MyIp}/32'
