Resources:
  OpsworksServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - opsworks.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: OpsworksServiceRole
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - cloudwatch:DescribeAlarms
            - cloudwatch:GetMetricStatistics
            - ec2:*
            - ecs:*
            - elasticloadbalancing:*
            - iam:GetRolePolicy
            - iam:ListInstanceProfiles
            - iam:ListRoles
            - iam:ListUsers
            - rds:*
            Resource:
            - "*"
          - Effect: Allow
            Action:
            - iam:PassRole
            Resource: "*"
            Condition:
              StringEquals:
                iam:PassedToService: ec2.amazonaws.com
  InstanceIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: opsworks-service
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - ec2:*
            - s3:*
            - opsworks:*
            - iam:PassRole
            Resource:
            - !Sub "arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:instance/*"
            Condition:
              StringEquals:
                iam:PassedToService: opsworks.amazonaws.com
  InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      InstanceProfileName: !Sub ${InstanceIAMRole}-Profile
      Path: /
      Roles:
        - !Ref InstanceIAMRole
